version: 3.7"

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: webvirtcloud:dev
    hostname: backend
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: gunicorn webvirtcloud.wsgi:application --bind 0.0.0.0:8000
    environment:
      DB_HOST: mariadb
      DB_PORT: 3306
      DB_NAME: webvirtcloud
      DB_USER: django
      DB_PASSWORD: django
      PYTHONOPTIMIZE: 1
      ANSIBLE_HOST_KEY_CHECKING: 0
      ANSIBLE_PARAMIKO_LOOK_FOR_KEYS: 0
      DJANGO_SETTINGS_MODULE: webvirtcloud.settings.develop
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6.10
    hostname: mariadb
    volumes:
      - ./.mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MARIADB_DATABASE: webvirtcloud
      MARIADB_USER: django
      MARIADB_PASSWORD: django
      MARIADB_ROOT_PASSWORD: root
  rabbitmq:
    image: rabbitmq:3.10.13
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest